//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAKE_CUSTOMIZE_DETAIL
    {
        public int DETAIL_ID { get; set; }
        public Nullable<int> CAKE_ID { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<int> CAKE_FLAVOUR_ID { get; set; }
        public Nullable<int> TIER_ORDER { get; set; }
        public Nullable<int> TIER_WEIGHT { get; set; }
        public Nullable<int> FLAVOUR_PRICE { get; set; }
    }
}
