//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAKE_CATEGORIES
    {
        public CAKE_CATEGORIES()
        {
            this.CAKES = new HashSet<CAKE>();
        }
    
        public int CAKE_CATEGORY_ID { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<CAKE> CAKES { get; set; }
    }
}
