//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAKE
    {
        public CAKE()
        {
            this.CAKE_EVENTS = new HashSet<CAKE_EVENTS>();
            this.CAKE_FLAVORS = new HashSet<CAKE_FLAVORS>();
            this.CAKE_TAGS = new HashSet<CAKE_TAGS>();
            this.CAKE_TIERS = new HashSet<CAKE_TIERS>();
        }
    
        public int CAKE_ID { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> MIN_WEIGHT { get; set; }
        public Nullable<int> MAX_WEIGHT { get; set; }
        public Nullable<int> MIN_TIERS { get; set; }
        public Nullable<int> MAX_TIERS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ESTIMATED_TIME { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<bool> DELIVERY { get; set; }
        public Nullable<int> IS_CUSTOMIZABLE { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> ADDITIONAL_PRICE { get; set; }
        public string CAKE_PHOTO { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> IS_APPROVED { get; set; }
        public Nullable<int> APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_ON { get; set; }
    
        public virtual CAKE_CATEGORIES CAKE_CATEGORIES { get; set; }
        public virtual ICollection<CAKE_EVENTS> CAKE_EVENTS { get; set; }
        public virtual ICollection<CAKE_FLAVORS> CAKE_FLAVORS { get; set; }
        public virtual ICollection<CAKE_TAGS> CAKE_TAGS { get; set; }
        public virtual ICollection<CAKE_TIERS> CAKE_TIERS { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
