//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAKE_IMAGES
    {
        public int CAKE_IMAGE_ID { get; set; }
        public Nullable<int> CAKE_ID { get; set; }
        public string IMAGE_PATH { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
    }
}
