//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_DATA
    {
        public int EMAIL_DATA_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> MAILED_ON { get; set; }
    }
}
