//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLAVOR
    {
        public FLAVOR()
        {
            this.CAKE_FLAVORS = new HashSet<CAKE_FLAVORS>();
        }
    
        public int FLAVOR_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
    
        public virtual ICollection<CAKE_FLAVORS> CAKE_FLAVORS { get; set; }
    }
}
