//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INQUIRY
    {
        public int INQUIRY_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> OBJECT_ID { get; set; }
        public Nullable<System.DateTime> INQUIRY_TIME { get; set; }
        public Nullable<int> INQUIRY_TYPE_ID { get; set; }
    }
}
