//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_TYPES
    {
        public ITEM_TYPES()
        {
            this.ORDER_DETAILS = new HashSet<ORDER_DETAILS>();
        }
    
        public int ITEM_TYPE_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<ORDER_DETAILS> ORDER_DETAILS { get; set; }
    }
}
