//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAILS
    {
        public int ORDER_DETAIL_ID { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public Nullable<int> ITEM_TYPE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<bool> IS_DELIVERED { get; set; }
        public Nullable<bool> IS_REJECTED { get; set; }
        public string REJECTED_REASON { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<bool> IS_CANCELLED { get; set; }
    
        public virtual ITEM_TYPES ITEM_TYPES { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
