//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public ORDER()
        {
            this.ORDER_DETAILS = new HashSet<ORDER_DETAILS>();
        }
    
        public int ORDER_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT_NO { get; set; }
        public string EMAIL { get; set; }
        public string GREETINGS { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<decimal> SHIPPING_CHARGES { get; set; }
        public Nullable<decimal> TOTAL_DISCOUNT { get; set; }
        public Nullable<decimal> FINAL_BILL { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public string REJECTED_REASON { get; set; }
        public string CUSTOMER_NAME { get; set; }
    
        public virtual ICollection<ORDER_DETAILS> ORDER_DETAILS { get; set; }
    }
}
