//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.PRODUCT_TAGS = new HashSet<PRODUCT_TAGS>();
        }
    
        public int PRODUCT_ID { get; set; }
        public int VENDOR_ID { get; set; }
        public int PRODUCT_SUB_CATEGORY_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string TIME_REQUIRED { get; set; }
        public string PRICE { get; set; }
        public string SERVES { get; set; }
        public Nullable<bool> DELIVERY { get; set; }
        public Nullable<int> IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string PRODUCT_PHOTO { get; set; }
        public Nullable<bool> IS_APPROVED { get; set; }
        public Nullable<int> APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_ON { get; set; }
    
        public virtual ICollection<PRODUCT_TAGS> PRODUCT_TAGS { get; set; }
        public virtual SUB_CATEGORIES SUB_CATEGORIES { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
