//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_CATEGORIES
    {
        public SUB_CATEGORIES()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int SUB_CATEGORY_ID { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
