//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_REVIEW
    {
        public int REVIEW_ID { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> RATING { get; set; }
        public string REVIEW { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    }
}
