//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodChapter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_CATEGORIES
    {
        public int VENDOR_CATEGORY_ID { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public Nullable<int> VENDOR_ID { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
    
        public virtual VENDOR VENDOR { get; set; }
    }
}
